"use client";

import type { ComponentProps, ReactNode } from "react";
import { BotIcon, UserIcon, WrenchIcon } from "lucide-react";
import { cn } from "@/lib/utils";
import { mono } from "@/lib/surfaces";

export type SpeakerKind = "user" | "agent" | "subagent" | "tool";

export interface SpeakerTurn {
  id: string;
  kind: SpeakerKind;
  name: string;
  detail?: string;
  text?: ReactNode;
}

const TONE: Record<SpeakerKind, string> = {
  user: "bg-muted text-muted-foreground",
  agent:
    "bg-[color-mix(in_oklch,var(--status-running)_14%,transparent)] text-foreground",
  subagent: "bg-accent text-accent-foreground",
  tool: "bg-muted/60 text-muted-foreground",
};

export function SpeakerIdentity({
  turns,
  variant = "turns",
  className,
  ...props
}: Omit<ComponentProps<"div">, "children"> & {
  turns: readonly SpeakerTurn[];
  variant?: "turns" | "model-attribution";
}) {
  if (variant === "model-attribution") {
    return (
      <div
        data-slot="speaker-identity"
        data-variant="model-attribution"
        className={cn("text-faint text-xs", className)}
        {...props}
      >
        {turns.map((turn) =>
          turn.detail ? (
            <span key={turn.id}>Generated by {turn.detail}</span>
          ) : null,
        )}
      </div>
    );
  }

  return (
    <div
      data-slot="speaker-identity"
      data-variant="turns"
      className={cn("flex w-full max-w-sm flex-col gap-3.5", className)}
      {...props}
    >
      {turns.map((turn) => (
        <div key={turn.id} data-speaker-kind={turn.kind} className="flex gap-2.5">
          <span
            aria-hidden="true"
            className={cn(
              "flex size-6 shrink-0 items-center justify-center rounded-lg",
              TONE[turn.kind],
              turn.kind === "subagent" && "rounded-full",
            )}
          >
            {turn.kind === "user" ? (
              <UserIcon className="size-3" />
            ) : turn.kind === "tool" ? (
              <WrenchIcon className="size-3" />
            ) : (
              <BotIcon className="size-3" />
            )}
          </span>

          <div className="flex min-w-0 flex-1 flex-col gap-0.5">
            <span className="flex items-baseline gap-1.5">
              <span className="text-[13px] font-medium">{turn.name}</span>
              {turn.detail && (
                <span className={cn(mono, "text-faint truncate")}>
                  {turn.detail}
                </span>
              )}
            </span>
            {turn.text !== undefined && turn.text !== "" && (
              <span className="text-muted-foreground text-[13.5px] leading-relaxed break-words">
                {turn.text}
              </span>
            )}
          </div>
        </div>
      ))}
    </div>
  );
}
